ALTER TABLE notes ADD COLUMN preview TEXT NOT NULL DEFAULT '';
ALTER TABLE notes ADD COLUMN word_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN task_done INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notes ADD COLUMN task_total INTEGER NOT NULL DEFAULT 0;
